/*
javazone-catalog-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package catalogclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FieldDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldDTO{}

// FieldDTO struct for FieldDTO
type FieldDTO struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type _FieldDTO FieldDTO

// NewFieldDTO instantiates a new FieldDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldDTO(name string, type_ string) *FieldDTO {
	this := FieldDTO{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewFieldDTOWithDefaults instantiates a new FieldDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldDTOWithDefaults() *FieldDTO {
	this := FieldDTO{}
	return &this
}

// GetName returns the Name field value
func (o *FieldDTO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FieldDTO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FieldDTO) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *FieldDTO) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FieldDTO) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FieldDTO) SetType(v string) {
	o.Type = v
}

func (o FieldDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *FieldDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFieldDTO := _FieldDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFieldDTO)

	if err != nil {
		return err
	}

	*o = FieldDTO(varFieldDTO)

	return err
}

type NullableFieldDTO struct {
	value *FieldDTO
	isSet bool
}

func (v NullableFieldDTO) Get() *FieldDTO {
	return v.value
}

func (v *NullableFieldDTO) Set(val *FieldDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldDTO(val *FieldDTO) *NullableFieldDTO {
	return &NullableFieldDTO{value: val, isSet: true}
}

func (v NullableFieldDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


